title = "Forest Hills Community of Christ"
baseURL = "https://compassionate-khorana-ffbc8f.netlify.app/"
languageCode = "en-us"
theme = "ananke_custom"
# themesDir = "../.."
# resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Forest Hills Community of Christ"
  text_color = ""
  author = ""
  favicon = "/congregation_logo.png"
  site_logo = "/forest_hills_logo.png"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-white"
  recent_posts_number = 2

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/cofchrist.foresthills"

# Menu links
[[menu.main]]
    name = "About Our Congregation"
    weight = 1
    url = "/about_congregation"
[[menu.main]]
    name = "Events"
    weight = 2
    url = "/events"
[[menu.main]]
   name = "Our Garden & Outreach"
   weight = 3
   url  = "/scripture_garden/"
[[menu.main]]
   name = "About Community of Christ"
   weight = 4
   url  = "/about_denomination/"
[[menu.main]]
   name = "For Latter-day Seekers"
   weight = 5
   url  = "/latter_day_seekers"
[[menu.main]]
   name = "Contact Us"
   weight = 6
   url  = "/contact_us/"